a: float32.mli float32.ml float32.c trigo_check3.ml
	ocamlc -c -custom float32.mli
	ocamlc -c -custom float32.ml
	ocamlc -c -custom float32.c
	ocamlc -c -custom trigo_check3.ml
	ocamlc -custom -o trigo_check3 float32.o float32.cmo trigo_check3.cmo 

